version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    env_file: .env
    networks:
      - backend_net
    volumes:
      - media_volume:/backend/media
    expose:
      - "8000"  # Make it visible to other containers
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    env_file: .env
    networks:
      - backend_net
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    depends_on:
      - backend
    restart: unless-stopped

networks:
  backend_net:

volumes:
  postgres_data:
  static_volume:
  media_volume:
