# Generated by Django 5.1.6 on 2025-03-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('products', '0002_product_artist_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('scarf', 'Платок'), ('hoodie', 'Толстовка'), ('sweatshirt', 'Свитшот'), ('painting', 'Картина'), ('t-shirt', 'Футболка'), ('pazzle', 'Пазл'), ('shopper', 'Шоппер')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
