# Generated by Django 5.1.6 on 2025-03-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('scarf', 'Платок'), ('hoodie', 'Толстовка'), ('sweatshirt', 'Свитшот'), ('painting', 'Картина'), ('tshirt', 'Футболка'), ('pazzle', 'Пазл'), ('shopper', 'Шоппер'), ('caps', 'Кепка')], max_length=50),
        ),
    ]
