# Generated by Django 5.1.6 on 2025-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='secondaryPhoto',
            field=models.ImageField(blank=True, upload_to='artists/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='artists/'),
        ),
    ]
