# Generated by Django 5.1.6 on 2025-03-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_secondaryphoto_alter_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='secondName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
