# Generated by Django 5.1.6 on 2025-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture of the user.', null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
